### ISSUE TITLE
broken parser for equipments

### ISSUE THREAD

**Issue by Kores** [TrinityCore/WowPacketParser#140]
Parser for save creatures equip to sql has been broken after 6.x.. Needed data exist in txt, but not in sql. For 5.x.x sniffs works fine.

Example from 5.4.7 dump:
http://pastebin.com/aVPaNVVR

Example from 6.0.3 dump:
http://pastebin.com/5bEMcyDp

Example  6.0.3 sniff:
http://rghost.ru/private/58955856/1bacdf17f3ed5810b8c38aaa91316367

**Comment by danlapps** [comment]
All paste or file deleted or removed.  Not quite sure what to look for here.  Can anyone explain better ?

**Comment by tkrokli** [comment]
This issue is useless in its current state, not even sure if it is valid anymore. I think @Kores meant to say that all equipped items on the NPCs/creatures used to be available info in the SQL produced from sniffs during 5.4.7, but no longer in 6.x. The evidence is long gone, though. Time to close this issue?

**Comment by Carbenium** [comment]
All pastes were removed. If still valid open a new issue.
