### ISSUE TITLE
Error: Failed writing ObjectNames

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#458]
Detected build: 7.0.3 22522
Targeted database: BattleForAzeroth

Description:

WowPacketParser.exe Error: 0 : System.ArgumentException: No se puede encontrar el valor solicitado 'Battleground'.
   en System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   en System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   en WowPacketParser.SQL.SQLDatabase.Get[T](RowList`1 rowList, String database) en D:\WowPacketParser\WowPacketParser\SQL\SQLDatabase.cs:línea 246
   en WowPacketParser.SQL.Builders.Miscellaneous.ObjectNames() en D:\WowPacketParser\WowPacketParser\SQL\Builders\Miscellaneous.cs:línea 48

**Comment by mdX7** [comment]
same thing as i already posted in https://github.com/TrinityCore/WowPacketParser/issues/455
I guess that line 48 in Miscellaneous.cs is refering to `return SQLUtil.Compare(Storage.ObjectNames, templateDb, StoreNameType.None);` for you. For me it's on line 52 actually, but it's likely exactly the same problem as in the issue above. Pull clean wpp repository and try again.

**Comment by mdX7** [comment]
turns out our `object_names` table in wpp database is a bit bugged. This is due to a change we made to ObjectTypes. Quick 'n dirty fix to 'unbug database': 
```sql
DELETE FROM ´object_names` WHERE `ObjectType`="Battleground" AND `ID`>11
```
The object type Unit is represented in enum as 5 in WPP, but in database object type 5 are battlegrounds.

To properly fix this we got three solutions:
1. Change the order here to be the same as in database: https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParser/Enums/ObjectType.cs#L3
2. Change the order in database to fit the one posted above
3. Use an own enum which is unrelated to wows objecttypes for `object_names` (I'd suggest this)

Summon @Shauren
